# Generated by Django 3.1.7 on 2021-04-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('required_stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('star_count', models.IntegerField()),
                ('student_1', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2', models.CharField(blank=True, max_length=100, null=True)),
                ('student_3', models.CharField(blank=True, max_length=100, null=True)),
                ('is_for_everyone', models.BooleanField()),
                ('questboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='questboard.questboard')),
            ],
        ),
    ]
